[2018-10-02 21:17:47] [    INFO] --- Setup logging. Log file: ./output/s1_p_2_2_4-2/CIFAR10/model_name=CNN_s1_2_2_4/no_cuda=True/seed=42/02-10-18-21h-17m-47s/logs.txt (setup.py:511)
[2018-10-02 21:17:47] [    INFO] --- Arguments saved to: ./output/s1_p_2_2_4-2/CIFAR10/model_name=CNN_s1_2_2_4/no_cuda=True/seed=42/02-10-18-21h-17m-47s/args.txt (setup.py:514)
[2018-10-02 21:17:47] [    INFO] --- Initialize Tensorboard SummaryWriter (setup.py:519)
[2018-10-02 21:17:52] [ WARNING] --- Git status is ignored! (RunMe.py:205)
[2018-10-02 21:17:52] [    INFO] --- Model CNN_s1_2_2_4 expects input size of (32, 32) (image_classification.py:60)
[2018-10-02 21:17:52] [    INFO] --- Loading CIFAR10 from:datasets/CIFAR10 (setup.py:233)
[2018-10-02 21:17:52] [    INFO] --- Verifying the dataset integrity - quick (dataset_integrity.py:182)
[2018-10-02 21:17:58] [    INFO] --- Newly measured timestamp: Tue Oct  2 20:27:15 2018 (dataset_integrity.py:188)
[2018-10-02 21:17:58] [   ERROR] --- The dataset has been modified. The last_modified field does not match: old[Tue Oct  2 20:23:10 2018] new[Tue Oct  2 20:27:15 2018] (dataset_integrity.py:194)
[2018-10-02 21:17:59] [    INFO] --- Dataset loaded as images (setup.py:267)
[2018-10-02 21:17:59] [    INFO] --- Setting up model CNN_s1_2_2_4 (setup.py:86)
[2018-10-02 21:17:59] [    INFO] --- Loading weights for data balancing (setup.py:101)
[2018-10-02 21:17:59] [    INFO] --- Begin training (image_classification.py:73)
[2018-10-02 21:18:04] [    INFO] --- val   epoch[-1]: Acc@1=8.900	Loss=2.3155	Batch time=0.025 (0.002 to load data) (evaluate.py:151)
[2018-10-02 21:18:38] [    INFO] --- val   epoch[0]: Acc@1=19.250	Loss=2.2360	Batch time=0.030 (0.002 to load data) (evaluate.py:151)
[2018-10-02 21:19:14] [    INFO] --- val   epoch[1]: Acc@1=21.500	Loss=2.1569	Batch time=0.034 (0.002 to load data) (evaluate.py:151)
[2018-10-02 21:19:52] [    INFO] --- val   epoch[2]: Acc@1=22.680	Loss=2.1041	Batch time=0.035 (0.003 to load data) (evaluate.py:151)
[2018-10-02 21:20:31] [    INFO] --- val   epoch[3]: Acc@1=23.800	Loss=2.0597	Batch time=0.036 (0.003 to load data) (evaluate.py:151)
[2018-10-02 21:21:12] [    INFO] --- val   epoch[4]: Acc@1=25.620	Loss=2.0232	Batch time=0.037 (0.003 to load data) (evaluate.py:151)
[2018-10-02 21:21:19] [    INFO] --- test  epoch[4]: Acc@1=27.230	Loss=2.0114	Batch time=0.037 (0.003 to load data) (evaluate.py:151)
[2018-10-02 21:21:19] [    INFO] --- Training completed (image_classification.py:91)
[2018-10-02 21:21:19] [    INFO] --- Time taken for train/eval/test is: 0:03:26 (RunMe.py:257)
