[2018-10-02 21:05:49] [    INFO] --- Setup logging. Log file: ./output/s1_p_2_2_4/CIFAR10/model_name=CNN_s1_2_2_4/optimizer_name=Adam/no_cuda=True/seed=42/02-10-18-21h-05m-49s/logs.txt (setup.py:511)
[2018-10-02 21:05:49] [    INFO] --- Arguments saved to: ./output/s1_p_2_2_4/CIFAR10/model_name=CNN_s1_2_2_4/optimizer_name=Adam/no_cuda=True/seed=42/02-10-18-21h-05m-49s/args.txt (setup.py:514)
[2018-10-02 21:05:49] [    INFO] --- Initialize Tensorboard SummaryWriter (setup.py:519)
[2018-10-02 21:05:53] [ WARNING] --- Git status is ignored! (RunMe.py:205)
[2018-10-02 21:05:53] [    INFO] --- Model CNN_s1_2_2_4 expects input size of (32, 32) (image_classification.py:60)
[2018-10-02 21:05:53] [    INFO] --- Loading CIFAR10 from:datasets/CIFAR10 (setup.py:233)
[2018-10-02 21:05:53] [    INFO] --- Verifying the dataset integrity - quick (dataset_integrity.py:182)
[2018-10-02 21:06:02] [    INFO] --- Newly measured timestamp: Tue Oct  2 20:27:15 2018 (dataset_integrity.py:188)
[2018-10-02 21:06:02] [   ERROR] --- The dataset has been modified. The last_modified field does not match: old[Tue Oct  2 20:23:10 2018] new[Tue Oct  2 20:27:15 2018] (dataset_integrity.py:194)
[2018-10-02 21:06:03] [    INFO] --- Dataset loaded as images (setup.py:267)
[2018-10-02 21:06:03] [    INFO] --- Setting up model CNN_s1_2_2_4 (setup.py:86)
[2018-10-02 21:06:03] [    INFO] --- Loading weights for data balancing (setup.py:101)
[2018-10-02 21:06:03] [    INFO] --- Begin training (image_classification.py:73)
[2018-10-02 21:06:09] [    INFO] --- val   epoch[-1]: Acc@1=8.900	Loss=2.3155	Batch time=0.032 (0.002 to load data) (evaluate.py:151)
[2018-10-02 21:06:57] [    INFO] --- val   epoch[0]: Acc@1=42.780	Loss=1.6103	Batch time=0.040 (0.003 to load data) (evaluate.py:151)
[2018-10-02 21:07:42] [    INFO] --- val   epoch[1]: Acc@1=49.890	Loss=1.4138	Batch time=0.039 (0.003 to load data) (evaluate.py:151)
[2018-10-02 21:08:40] [    INFO] --- val   epoch[2]: Acc@1=51.580	Loss=1.3538	Batch time=0.042 (0.003 to load data) (evaluate.py:151)
[2018-10-02 21:09:30] [    INFO] --- val   epoch[3]: Acc@1=53.330	Loss=1.3193	Batch time=0.041 (0.003 to load data) (evaluate.py:151)
[2018-10-02 21:10:15] [    INFO] --- val   epoch[4]: Acc@1=53.390	Loss=1.3209	Batch time=0.041 (0.003 to load data) (evaluate.py:151)
[2018-10-02 21:10:22] [    INFO] --- test  epoch[4]: Acc@1=52.940	Loss=1.3146	Batch time=0.036 (0.002 to load data) (evaluate.py:151)
[2018-10-02 21:10:22] [    INFO] --- Training completed (image_classification.py:91)
[2018-10-02 21:10:22] [    INFO] --- Time taken for train/eval/test is: 0:04:28 (RunMe.py:257)
